### ISSUE TITLE
MetGene Metabolites Node throws error in Use Case 13

### ISSUE THREAD

**Issue by giacomomarino** [MaayanLab/playbook-partnership#105]
Seems to happen with the default inputs provided for the workflow --> 
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
https://playbook-workflow-builder.cloud/report/4d1fa785-255a-c61c-4a8f-b5ad5de0a2c2

**Comment by susrinivasan** [comment]
This issue is fixed now. Thanks for pointing it out.
