### ISSUE TITLE
Add Icons for exRNA metanodes

### ISSUE THREAD

**Issue by HadleyKing** [MaayanLab/playbook-partnership#107]
The icon for the gene set and variant set make sense. The icons for variant table and gene table do not…. I know that you were trying to have different icons for a set result vs a table result.

https://playbook-workflow-builder.cloud/report/cc338d00-d22e-08b1-3b74-21710dec3847

**Comment by u8sand** [comment]
@MmPersida

**Comment by u8sand** [comment]
This was since addressed
