### ISSUE TITLE
Use Case 13: Prioritizing Targets for Individual Cancer patients [MetGENE Metabolites]

### ISSUE THREAD

**Issue by jeet-vora** [MaayanLab/playbook-partnership#108]
SyntaxError: Unexpected token '<' "<!DOCTYPE "….. is not valid JSON

<img width="1340" alt="image" src="https://github.com/nih-cfde/playbook-partnership/assets/25825266/aa55759b-33e6-4ad2-8a9a-c16617a09726">

**Comment by u8sand** [comment]
Metabolomics fixed this
