### ISSUE TITLE
Workflow manifest JSON

### ISSUE THREAD

**Issue by HadleyKing** [MaayanLab/playbook-partnership#11]
@u8sand mentioned in the last meeting on 12/01/22 that he would provide an example JSON file for the workflow manifest for BCO conversion. Could you attach it here when it is ready?

**Comment by u8sand** [comment]
Hi @HadleyKing

I created an initial conversion script and added an API endpoint which exports any workflow as a BCO JSON.
See: https://github.com/nih-cfde/playbook-partnership/compare/dev...bco

Once deployed, the graph endpoint can be accessed by replacing `/graph/{some_id}` with `/api/bco/{some_id}`.

My first pass at this is attached  (this is the export of a workflow I made): [playbook-partnership-bco.json.txt](https://github.com/nih-cfde/playbook-partnership/files/10177332/playbook-partnership-bco.json.txt)

Some obvious issues:
- it's a bit tricky to specify input of one pipeline step is output of another please advise. I have opted for a JSON-Pointer style notation given an in-memory json data structure of the runtime.
- I reference a script executor but I haven't implemented that yet
- not sure what goes in etag/object_id please advise
- will need to include version/authors of the edges, this information needs to get put into metanode's `meta` fields
- A question: the example I was given to work from had some inconsistencies like "step_number: number" vs "step: string" in different sections. Is this intended.

**Comment by HadleyKing** [comment]
@kee007ney
Which BCO did you provide for an example?

**Comment by u8sand** [comment]
Attached is the original example I was given (.json.txt since github apparently doesn't like .json)
[CopyNumberCounterBCO.json.txt](https://github.com/nih-cfde/playbook-partnership/files/10177317/CopyNumberCounterBCO.json.txt)

**Comment by HadleyKing** [comment]
@u8sand 
- The scema repo is here: https://gitlab.com/IEEE-SA/2791-object/ieee-2791-schema
- We have some documentation here: https://docs.biocomputeobject.org/user_guide/

> I created an initial conversion script and added an API endpoint which exports any workflow as a BCO JSON. See: [dev...bco](https://github.com/nih-cfde/playbook-partnership/compare/dev...bco)
> 
> Once deployed, the graph endpoint can be accessed by replacing `/graph/{some_id}` with `/api/bco/{some_id}`.
> 
> My first pass at this is attached (this is the export of a workflow I made): [playbook-partnership-bco.json.txt](https://github.com/nih-cfde/playbook-partnership/files/10177332/playbook-partnership-bco.json.txt)
> 
> Some obvious issues:
> 
> * it's a bit tricky to specify input of one pipeline step is output of another please advise. I have opted for a JSON-Pointer style notation given an in-memory json data structure of the runtime.

The JSON pointer satisfies the standard. That is a good use of it. 

> * I reference a script executor but I haven't implemented that yet

Great. 

> * not sure what goes in etag/object_id please advise

ETag and Object Id are described here: https://docs.biocomputeobject.org/top-level/

> * will need to include version/authors of the edges, this information needs to get put into metanode's `meta` fields

The paradigm we have been using is to have as much as possible filled out automatically, and then use either our BCO portal to finish it or another manual process. Happy to explore this further.

> * A question: the example I was given to work from had some inconsistencies like "step_number: number" vs "step: string" in different sections. Is this intended.

You are referring to 
https://gitlab.com/IEEE-SA/2791-object/ieee-2791-schema/-/blob/master/description_domain.json#L100
vs 
https://gitlab.com/IEEE-SA/2791-object/ieee-2791-schema/-/blob/master/parametric_domain.json#L39 ?
It is not necessarily intended, but your interpretation is correct.
