### ISSUE TITLE
Downscored drugs have positive z-score

### ISSUE THREAD

**Issue by lachmann12** [MaayanLab/playbook-partnership#114]
in use case 25 there is a step called  called "Down Scored Drugs" After the filter there are only drugs with positive z-score

**Comment by u8sand** [comment]
@lachmann12 I specifically reverse the direction of the zscore since we're looking at the significance of the down drugs, did you find this too confusing? I suppose I can instead keep them negative and just reverse the sorting..

**Comment by lachmann12** [comment]
with any of these processing steps they have to be very clear. Otherwise, the chance of getting a wrong pipeline when chaining multiple is very high. e.g. P(misinterpreting a step)=0.1, with 5 steps chance of correct result (1-0.1)^5<0.6. (yay i can do basic probability). I bet each error probability is conditional given the step P(misinterpreting a step | step). Would be fun if there was a way to know. e.g. have multiple choice for each. that could tell you where potential problems could be. (it's a bit out there)

**Comment by u8sand** [comment]
Replaced by #230
