### ISSUE TITLE
Use Case 3 - Input File

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/playbook-partnership#143]
When I update the input- either clicking example or uploading a file- Gene Signature through an error as below. 
`ProcessError: [components.data.gene_signature.gene_signature]: Process exited with unexpected code 1`

@u8sand

**Comment by u8sand** [comment]
The example is not compatible with the format expected of a Gene Signature this would be fixed by #76 

Here is an example gene signature file:
[sig.csv](https://github.com/nih-cfde/playbook-partnership/files/13494264/sig.csv)
