### ISSUE TITLE
Graph mode data bug in data metanodes

### ISSUE THREAD

**Issue by seankim658** [MaayanLab/playbook-partnership#148]
![image](https://github.com/nih-cfde/playbook-partnership/assets/33474168/be917bd8-2e42-474a-994a-c7aa6ba6918e)

This bug only occurs in graph mode, have not seen it in the prototype mode. It isn't a breaking bug, things still work but it is confusing to the end user that they have to wait a couple seconds longer. 

Occurs with a couple of GlyGen's data metanodes that have somewhat long(er) backend process metanode logic. In the case of the protein set backend, multiple API calls have to be made to grab the final data. Likely what is happening is that pressing on the card for the process metanode immediately calls the output data metanode and within the data metanode's `.view()` function the input parameter `data` is being read before the backend promise (API calls) are completed. 

I suspect some state logic will need to be implemented in order to catch this error from being thrown to the frontend. 

@u8sand Pat and I were wondering whether you would like us to implement this logic internal to our metanodes or if a fix with a larger scope would be more appropriate?

**Comment by u8sand** [comment]
Hi @seankim658 this is already fixed in #92 and which will make it to main in the near future

**Comment by seankim658** [comment]
Awesome, thank you. I will close this issue.
