### ISSUE TITLE
Stuck when selecting a bar plot before the data was ready

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#162]
https://playbook-workflow-builder.cloud/graph/e4aacf7a-4772-f8aa-5eba-6acee985623c

**Comment by u8sand** [comment]
![image](https://github.com/nih-cfde/playbook-partnership/assets/1341861/7534c1a9-1572-4a3f-8366-edd9d4637fc4)
You need to click one of these buttons

**Comment by u8sand** [comment]
I auto-select top 10 for now which hopefully makes it more obvious that these buttons are clickable to change it

**Comment by AviMaayan** [comment]
I think the issue is resolved because some other part was fixed... I can no longer reproduce the issue.

**Comment by u8sand** [comment]
Yeah, before it would not auto-select a value so if you just proceed it would be "waiting for input" -- I now auto-select top 10 so this will not happen anymore
