### ISSUE TITLE
When trying to get expression data from ARCHS4, the table looks empty but the data is there

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#164]
<img width="1391" alt="Screen Shot 2024-03-21 at 9 27 09 PM" src="https://github.com/nih-cfde/playbook-partnership/assets/12749033/92589924-7434-47ee-b678-3f6832f81312">

**Comment by u8sand** [comment]
Sorry this and #163 are a very recent reversion I introduced.. found the issue and deploying the fix now
