### ISSUE TITLE
Some cards are not clickable here

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#165]
https://playbook-workflow-builder.cloud/graph/a5b375e6-9db8-bb99-20ca-6effa488461e/extend

<img width="1388" alt="Screen Shot 2024-03-21 at 9 29 05 PM" src="https://github.com/nih-cfde/playbook-partnership/assets/12749033/39df5004-b78c-4c45-a8aa-11b5eb9af956">

**Comment by u8sand** [comment]
This is by design, these cards require multiple inputs and only one is satisfied. Open to alternative display suggestions

**Comment by AviMaayan** [comment]
That makes sense... I would add a pop-up or a tool-tip that explains this... ideally with what additional inputs are expected (if not too hard to implement)
