### ISSUE TITLE
Update favicon with new logo

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#196]
<img width="81" alt="Screenshot 2024-05-21 at 12 10 32 PM" src="https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/12749033/a9762e4d-92f8-4e1e-9e26-606958f79784">

**Comment by AviMaayan** [comment]
This is just the old logo...

**Comment by u8sand** [comment]
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/6e011454-bbaa-4c0b-9754-1dc382273efe)

is it cached?

**Comment by AviMaayan** [comment]
The favicon is fixed. It looks good to me...
