### ISSUE TITLE
Missing OpenAI key causes exception

### ISSUE THREAD

**Issue by pmcneely** [MaayanLab/playbook-partnership#199]
Is an OpenAI key planned to be a required part of the system?
Key error message on "File Upload" --> "Submit":
```
{"name":"Error","source":"server","message":"The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).","stack":"Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' })
```
Full error image:
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/22220587/c3e9b87a-6f69-4f4f-a6bf-a0447f91be20)

**Comment by u8sand** [comment]
Sorry about this -- it'll now run without the key but obviously openai-powered features won't work
