### ISSUE TITLE
White space after you press the start chat button

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#203]

**Comment by u8sand** [comment]
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/383aa3de-ba53-468f-a0b1-b36c00b52fb1)
are you talking about between "Chat" and the message?

This is typical of any chat application interface -- it's so the input field doesn't move as messages are created..

e.g.
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/89060ed3-9ed2-4ea8-9223-a43429050d26)

**Comment by AviMaayan** [comment]
Ok... Can you add this to the page so it does not look empty...
![Screenshot 2024-05-28 at 10 27 55 AM](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/12749033/4be8ddc7-cacb-4b51-a2dc-d6c6a5fbd89e)

**Comment by AviMaayan** [comment]
Also, we should add more buttons with examples from the published workflows...

**Comment by u8sand** [comment]
Fixed in b4c068939e47434155a2438b98bc8818b0cfea92
