### ISSUE TITLE
Does not look like there are any "Viewer" metanodes listed here

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#204]
<img width="1249" alt="Screenshot 2024-05-24 at 11 54 39 PM" src="https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/12749033/1d4cef45-26e8-4fc3-a811-a9291e994b3f">

**Comment by u8sand** [comment]
@AviMaayan A "Viewer" is just the rendering of any "Data" metanode -- so essentially any "Data type" on this table is also "Viewer" -- should I change it to say "Viewer" rather than "Data" ?

**Comment by AviMaayan** [comment]
I think the term viewer would be helpful to distinguish visualization "terminal" metanodes to be consistent with the paper (?)
