### ISSUE TITLE
The minimize hamburger should look like a minimize icon (-)

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#213]
One of these will do:

<img width="493" alt="Screenshot 2024-06-06 at 8 09 41 PM" src="https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/12749033/66f767d3-f800-48a3-9a3c-362483b1febd">

**Comment by u8sand** [comment]
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/f71dbe93-a10e-4685-ace7-c451252d1574)
🖵 🗔 🗕 🗖 🗗 ⎚ 🗙 ⌧
This is a UTF-8 minimize icon, open for alternatives -- ideally an SVG icon

**Comment by AviMaayan** [comment]
I think the 3rd, 4th, and 7th should work...

**Comment by u8sand** [comment]
Those fonts will be different on different systems so how about
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/5cc10209-9c9c-4d98-8f6b-ac9519c6dd0b)
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/ecdd3c46-360e-44f0-b8ad-377578722e20)
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/8f7cd10b-5cd9-4fa7-8c4a-488140141666)

**Comment by AviMaayan** [comment]
I like these better!
