### ISSUE TITLE
Issue: Website crashes upon addition of a counts matrix

### ISSUE THREAD

**Issue by reductiveminded** [MaayanLab/playbook-partnership#226]
**Description:**
My name is Matthew Marino. I am a CFDE GlyGEN summer intern working under Jeet Vora and Rene Ranzinger. I am currently trying to create multiomics workflows starting with transcriptomics and proteomics data.
Upon uploading a file to the node "Gene Count Matrix" I encounter the following error (screenshot below). Essentially the website crashes and I lose all progress on my workflow. I am also unable to perform any downstream data transformation (such as log2 transformation of the counts) because the matrix does not upload correctly. 
I am using Brave browser on a windows operating system.

Image of Error:

![Error_when_adding_counts_image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/104637642/36001810-a925-40cf-b663-2f2b91b8d0a4)

URL when error is displayed:
https://playbook-workflow-builder.cloud/graph/2ed94da4-7c2a-0ca0-d40e-71c0e76d4867/node/a25f7836-ebc0-526b-2552-7ec0e2b0ac05

Here is the counts matrix I have tried to upload it is from published dataset from my previous lab (https://doi.org/10.1021/acs.jproteome.3c00838). I used R studio to remove duplicates and 0 value reads and this is from bulk RNA Seq. The file size is 874 KB.

[counts_filt_multi.txt](https://github.com/user-attachments/files/15917915/counts_filt_multi.txt)

**Comment by u8sand** [comment]
Hi @reductiveminded -- thank you for reporting this issue.

The issue is that the data file is not in any obvious format. Please export it from R as a .tsv or a .csv and upload that (with the proper extension).

However, we definitely should not crash the page when this kind of error occurs but should report the error message to the user properly.

**Comment by reductiveminded** [comment]
Hello @u8sand -- thank you for your response. 

I will try again with .csv format and let you know how it goes.
