### ISSUE TITLE
Adding a Metadata Matrix

### ISSUE THREAD

**Issue by reductiveminded** [MaayanLab/playbook-partnership#233]
**Description:**
I am trying to upload a metadata matrix (pairwise comparison between 0 minute stimulation and 30 minute stimulation). I am following the format as seen in this video: https://www.youtube.com/watch?v=BY0VGFP8wZc
Whenever I upload the matrix I get this error: Image below
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/104637642/6945d65e-b484-48ff-8f5a-0b85abd7d9a6)

Here is the image of the metadata matrix (in .csv format)
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/104637642/52e351b5-7279-4c5b-923e-e2b3b0643a3f)

**Comment by u8sand** [comment]
Thanks for reporting this. your file does look like it's formatted properly. This is a recent reversion which has now been fixed and the update is being deployed.
