### ISSUE TITLE
Add versions of needed packages 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#3]
One of the comments from the hackathon was to include version numbers of installed software packages that were tried and tested.

**Comment by u8sand** [comment]
Can you clarify which versions this is referring to?

- In terms of the javascript dependency versions, this is handled by the `package.json` files
- In terms of the python dependency versions, this should be in the `requirements.txt` files (though currently we aren't using explicit versions)
- Both of these are successfully used to construct the `Dockerfile` which can be used to build this in a (mostly) device agnostic way.
- In terms of the dependent software like NodeJS or Python, we could capture this somewhere, currently the latest versions work and likely many versions older.
