### ISSUE TITLE
Try to create use case 1 - got stuck here

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#31]
https://playbook-partnership.maayanlab.cloud/graph/7006b674-1b23-8cd9-498c-595e1774ace0

The prompt is:

It is known that Clonidine and Propranolol cause a mysterious hypertension. Using the L1000 data, we want to find genes that are up- or down-regulated by these drugs and see if any of these drugs overlap with genes that are known to be associated with hypertension from GWAS Catalog, mouse phenotypes, and HPO.

**Comment by u8sand** [comment]
This should be fixed with ea55d772268dd2a4e7f5061fce0b279830899fb2
