### ISSUE TITLE
Failed to generate a SuperVenn from a GMT

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#45]
https://playbook-partnership.dev.maayanlab.cloud/graph/f37a887d-e364-0c00-d38f-4d7b160960c1

**Comment by u8sand** [comment]
My guess is hyposet doesn't have enough memory to process this particular gmt (i.e. the supervenn layout algorithm uses too much memory), we can try just giving that service more resources

**Comment by u8sand** [comment]
Update: it was actually just timing out, I increased cpu a bit and the timeout and it worked now.
