### ISSUE TITLE
This request for a SuperVenn was never executed: https://playbook-partnership.dev.maayanlab.cloud/graph/3caec8e7-4bc9-9331-f46d-1ce7ebff7512

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#46]

**Comment by u8sand** [comment]
The node before is a prompt node and was not submitted

**Comment by u8sand** [comment]
"Fixed" in 6b21c9773e0d597626acd92fb12d1405e553b3a2 by adding an indicator to the breadcrumbs to alert the user when a prompt node wasn't submitted
