### ISSUE TITLE
Add a way to label uploaded gene set libraries

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#47]
It would be great if there was an optional way to add a short description or a title that describes the GMT file that you upload.
<img width="1595" alt="Screen Shot 2023-03-18 at 1 54 42 PM" src="https://user-images.githubusercontent.com/12749033/226125702-ff487278-3e62-4520-9305-6bf607dcc2ca.png">

**Comment by u8sand** [comment]
Fixed in 1055dcb8f7de4d2a7df8f87a4ec0378aed5ca063
