### ISSUE TITLE
Error trying to create a SuperVenn from three concatenated small GMTs

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#48]
https://playbook-partnership.dev.maayanlab.cloud/graph/e911fe95-bd9e-c578-6cc8-8982c0d92fab
<img width="1400" alt="Screen Shot 2023-03-18 at 2 15 18 PM" src="https://user-images.githubusercontent.com/12749033/226126406-f54bd45f-7db7-40ec-9de9-65afcb00b8e8.png">

**Comment by u8sand** [comment]
You say "small" but there are 25 genesets here which seems to be approaching the limit for this service's current setup. I'll need to look into the scaling of the supervenn algorithm to see if supporting this many sets and more is practical. Maybe we need to make our own layout algorithm..

**Comment by u8sand** [comment]
You can now manipulate genesets to get a smaller GMT for this workflow. I think improving hyposet is out of scope for now
