### ISSUE TITLE
SuperVenn for many gene sets is not executing

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#52]
This playbook for a diabetes use case is not working: https://playbook-partnership.dev.maayanlab.cloud/graph/49219e6e-e333-a156-f64b-3cfd761d8883

SyntaxError: Unexpected token < in JSON at position 0

**Comment by u8sand** [comment]
Duplicate of #48 

25 genesets is proving too many for the hyposet service (which uses the supervenn layout algorithm)
