### ISSUE TITLE
Variant card example does not resolve

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#53]
https://playbook-partnership.dev.maayanlab.cloud/graph/0c59a3d5-052d-64ed-78fe-f05e40f8f3b0
<img width="875" alt="Screen Shot 2023-03-20 at 10 29 44 AM" src="https://user-images.githubusercontent.com/12749033/226371181-81d926b9-4a16-4284-aa3b-2c155dfbdf3b.png">

**Comment by u8sand** [comment]
This is unfortunately because the Mount Sinai DMZ blocks connections to this service. This happens with several other services as well on the dev deployment.

**Comment by u8sand** [comment]
Fixed on https://dev.playbook-workflow-builder.cloud/
