### ISSUE TITLE
Clicking on the report view before starting any workflow produces a blank page.

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#59]
Either say that "No workflow was constructed yet" or disable the button.
<img width="1573" alt="Screen Shot 2023-03-30 at 10 08 11 AM" src="https://user-images.githubusercontent.com/12749033/228863371-ac22e017-bc57-4604-a28b-fddf65900602.png">

**Comment by AviMaayan** [comment]
<img width="1573" alt="Screen Shot 2023-03-30 at 10 09 59 AM" src="https://user-images.githubusercontent.com/12749033/228863591-99802714-d51b-4348-8dc1-298ac8c09ab0.png">

**Comment by u8sand** [comment]
Already addressed in dev
![image](https://user-images.githubusercontent.com/1341861/228883618-9bd21528-bcd9-413e-8c1c-f91419b40216.png)
